import {Certification} from "@/app/types/dataType";
import {Education} from "@/app/types/dataType";
import {Internship} from "@/app/types/dataType";


export const certificationsData: Certification[] = [

    {
        id: '1',
        organizationName: 'Oracle',
        organizationLogo: '/logo/organizations/oracle.png',
        courseName: 'Oracle Certified Professional: Java SE 17 Developer',
        certificationImage: '/certificates/java17.jpg',
    },
    {
        id: '2',
        organizationName: 'Huawei',
        organizationLogo: '/logo/organizations/huawei.png',
        courseName: 'Huawei Certified Specialist Associate Sales-IP Network',
        certificationImage: '/certificates/huawei.jpg',
    },
    {
        id: '3',
        organizationName: 'Simplilearn',
        organizationLogo: '/logo/organizations/simplilearn.jpg',
        courseName: 'Getting Started with JUnit',
        certificationImage: '/certificates/junit.jpg',
    },
    {
        id: '4',
        organizationName: 'Coursera - AWS',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'AWS Cloud Technical Essentials',
        certificationImage: '/certificates/aws.jpg',
    },
    {
        id: '5',
        organizationName: 'LinkedIn Learning',
        organizationLogo: '/logo/organizations/linkedin.jpg',
        courseName: 'GitHub Career Essentials – Professional Certificate',
        certificationImage: '/certificates/github.jpg',
    },

    {
        id: '6',
        organizationName: 'Coursera',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'Introduction to Test Automation with Selenium and Java',
        certificationImage: '/certificates/selenium.jpg',
    },
    {
        id: '7',
        organizationName: 'Simplilearn',
        organizationLogo: '/logo/organizations/simplilearn.jpg',
        courseName: 'Angular Basics',
        certificationImage: '/certificates/angular.jpg',
    },
    {
        id: '8',
        organizationName: 'Coursera',
        organizationLogo: '/logo/organizations/coursera.jpg',
        courseName: 'Building CI/CD Pipelines with Jenkins (Declarative & IaC)',
        certificationImage: '/certificates/jenkins.jpg',
    },
    {
        id: '9',
        organizationName: 'Simplilearn',
        organizationLogo: '/logo/organizations/simplilearn.jpg',
        courseName: 'Containerization Basics with Docker',
        certificationImage: '/certificates/docker.jpg',
    },
    {
        id: '10',
        organizationName: 'Oracle',
        organizationLogo: '/logo/organizations/oracle.png',
        courseName: 'Oracle Certified Professional: Java SE 21 Developer',
        certificationImage: '/certificates/java21.jpg',
    },
];

export const educationsData: Education[] = [
    {
        logo: '/logo/school-logo/bts.png',
        schoolName: 'Ibn Sina Technical High School - BTS',
        location: 'Kenitra, Morocco',
        degree: 'Higher Technician Certificate',
        major: 'Information System Development',
        startYear: '2018',
        endYear: '2020',
        isGraduated: true,
    },
    {
        logo: '/logo/school-logo/UIT.png',
        schoolName: 'Ibn Tofail University - Faculty of Sciences',
        location: 'Kenitra, Morocco',
        degree: 'Bachelor’s Degree',
        major: 'Mathematics & Computer Sciences',
        startYear: '2020',
        endYear: '2021',
        isGraduated: true,
    },
    {
        logo: '/logo/school-logo/ensa.png',
        schoolName: 'The National School of Applied Sciences',
        location: 'Berrechid, Morocco',
        degree: 'Engineer’s Degree',
        major: 'Computer Engineering',
        startYear: '2021',
        endYear: '2024',
        isGraduated: true,
    },
];

export const internshipsData: Internship[] = [
    {
        id: '1',
        position: 'Software Engineer Intern',
        company: 'Capgemini Engineering',
        companyLogo: '/logo/companies/cap.png',
        location: 'Casablanca, Morocco',
        startDate: 'Fev 2024',
        endDate: 'Jun 2024',
        status: 'completed',
        topic: 'Digitalization Of the Onboarding Process for New Hires and Monitoring the Skill Development of Capgemini Consultants: « Welcome In » Platform',
        tasks: [],
        technologies: ['Figma', 'NextJs', 'NodeJs', 'TailwindCss', 'MUI', 'TypeScript', 'NodeMailer','Strapi CMS', 'AWS', 'Docker', 'UML', 'BPMN', 'MySql', 'JWT', 'Agile/Scrum'],
        uiImages: [
            '/images/cap-project/ui-work-1.png',
            '/images/cap-project/ui-work-2.png',
            '/images/cap-project/ui-work-3.png',
            '/images/cap-project/ui-work-4.png',
            '/images/cap-project/ui-work-5.png',
            '/images/cap-project/ui-work-6.png',
            '/images/cap-project/ui-work-7.png',
            '/images/cap-project/ui-work-8.png',
            '/images/cap-project/ui-work-9.png',
            '/images/cap-project/ui-work-10.png',
            '/images/cap-project/ui-work-11.png',
            '/images/cap-project/ui-work-12.png',
            '/images/cap-project/ui-work-13.png',
            '/images/cap-project/ui-work-14.png',
            '/images/cap-project/ui-work-15.png',
        ],
        width: 40,
        height: 40,
    },
    {
        id: '2',
        position: 'Software Engineer - Spring-boot/ReactJs',
        company: 'Info Etoile',
        companyLogo: '/logo/companies/info-etoile.png',
        location: 'Kenitra, Morocco',
        startDate: 'Jul 2023',
        endDate: 'Sep 2023',
        status: 'completed',
        topic: 'Integrated Management of Jobs and Recruitment Process, « CareerHub » Platform',
        tasks: [],
        technologies: ['UML', 'ReactJS', 'Spring boot', 'Spring security', 'JDK17','Bootstrap', 'Axios', 'MySql'],
        uiImages: [
            '/images/info-project/ui-work-1.png',
            '/images/info-project/ui-work-2.png',
            '/images/info-project/ui-work-3.png',
            '/images/info-project/ui-work-4.png',
            '/images/info-project/ui-work-5.png',
            '/images/info-project/ui-work-6.png',
            '/images/info-project/ui-work-7.png',
            '/images/info-project/ui-work-8.png',
            '/images/info-project/ui-work-9.png',
            '/images/info-project/ui-work-10.png',
            '/images/info-project/ui-work-11.png',
            '/images/info-project/ui-work-12.png',
            '/images/info-project/ui-work-13.png',
            '/images/info-project/ui-work-14.png',
        ],
        width: 90,
        height: 90,
    },
    {
        id: '3',
        position: 'Web Developer - PHP/Laravel',
        company: 'Web Eco',
        companyLogo: '/logo/companies/webeco.png',
        location: 'Kenitra, Morocco',
        startDate: 'Jul 2022',
        endDate: 'Aug 2022',
        status: 'completed',
        topic: 'IT Ticketing System',
        tasks: [],
        technologies: ['Laravel', 'PHP', 'HTML', 'CSS', 'JQuery', 'JavaScript', 'MySql', 'PhpMyAdmin'],
        uiImages: [
            '/images/webeco-project/ui-work-1.png',
            '/images/webeco-project/ui-work-2.png',
            '/images/webeco-project/ui-work-3.png',
            '/images/webeco-project/ui-work-4.png',
            '/images/webeco-project/ui-work-5.png',
            '/images/webeco-project/ui-work-6.png',
            '/images/webeco-project/ui-work-1-6.png',
            '/images/webeco-project/ui-work-2-6.png',
            '/images/webeco-project/ui-work-7.png',
            '/images/webeco-project/ui-work-8.png',
            '/images/webeco-project/ui-work-9.png',
            '/images/webeco-project/ui-work-10.png',
            '/images/webeco-project/ui-work-11.png',
            '/images/webeco-project/ui-work-12.png',
            '/images/webeco-project/ui-work-13.png',
            '/images/webeco-project/ui-work-14.png',
        ],
        width: 60,
        height: 40,
    },
    {
        id: '4',
        position: 'Web developer — PHP',
        company: 'The court of appeal',
        companyLogo: '/logo/companies/courDappel.png',
        location: 'Kenitra, Morocco',
        startDate: 'Jul 2019',
        endDate: 'Aug 2019',
        status: 'completed',
        topic: 'Internal Library Management System',
        tasks: [
            'Creating micro-interactions',
            'Transition animations',
            'Performance optimization',
            'Animation documentation',
        ],
        technologies: ['Merise', 'PhpMyAdmin', 'PHP', 'CSS', 'HTML'],
        uiImages: [
            '/images/court-project/ui-work-1.jpg',
            '/images/court-project/ui-work-2.jpg',
            '/images/court-project/ui-work-3.jpg',
            '/images/court-project/ui-work-4.jpg',
        ],
        width: 40,
        height: 40,
    },
];